version: '3'

services:
  mantos_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  mantos_app:
    image: mantos_app
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mantos_database
    environment:
      DATABASE_URL: postgresql://app_user:app_password@mantos_database:5432/app_db

volumes:
  pgdata: